# display
DISPLAY_WIDTH = 1200
DISPLAY_HEIGHT = 700

TARGET_FPS = 60

# closed system
CLOSED_SYSTEM_RENDER_SURFACE_SIZE = (900, 500)

# simulation
PARTICLE_RADIUS = 10

GAS_CONSTANT = ...
BOLTZMANNS_CONSTANT = 1.38e-23
